version: '3.3'

services:
  web:
    image: wordpress:latest
    ports:
      - "8081:80"
    depends_on:
      - "db"
    networks:
      - public
      - internal
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=my-secret-pw
      - WORDPRESS_DB_NAME=wordpressdb
      - WORDPRESS_TABLE_PREFIX=hj

  db:
    image: mysql:5.7
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wordpressdb

networks:
  public:
  internal:
    internal: true

