version: '3.9'

services:
  wordpress:
    image: wordpress:php8.0-fpm-alpine
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - "db"
    networks:
      - public
      - internal
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=my-secret-pw
      - WORDPRESS_DB_NAME=wordpressdb
      - WORDPRESS_TABLE_PREFIX=hj
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    networks:
      - internal
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wordpressdb
    volumes:
      - db:/var/www/html

networks:
  public:
  internal:
    internal: true

volumes:
  wordpress:
  db: